# -*- coding: utf-8 -*-
"""labcycle1_qstion4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7Exxlf7UEzGJUdafqUmvLw9BQxawitm

3. Develop a program to perform the following task  
a. Define a function to check whether a number is happy or not.   
b. Define a function to print all happy numbers within a range.   
c. Define a function to print first N happy numbers.
"""

def check_happy(n):  #function to check if the given number is happy
  sqr=sum=0
  status="sad"
  for i in range(100):
    while n>0:
      dig=n%10
      sqr=dig**2
      sum+=sqr
      n=n//10

    
    if sum==1:
      status="happy"
      break
    else:
      n=sum  
      sum=0
  return status

def happy_range(start,stop):   #function to check if the numbers within a range y is happy
  happy_nums=[]
  for i in range(start,stop):
    status=check_happy(i)
    if status=="happy":
      happy_nums.append(i)
  return happy_nums


def n_happy(n):     #function to check if the numbers until N is happy 
  happy_nums=[]
  i=1
  happy_ct=0
  while happy_ct<n:
    status=check_happy(i)
    if status=="happy":
      happy_nums.append(i)
      happy_ct+=1
    i+=1
    
  return happy_nums


num=int(input("enter the number to check if "))
print(num," is ",check_happy(num))


start=int(input("enter the start to check: "))
stop=int(input("enter the end to check: "))
print("happy numbers from ",start,"and",stop,"are: ",happy_range(start,stop))


n=int(input("enter the n to check for first n happy numbers "))
print("First N happy numbers are\t",n_happy(n))