# -*- coding: utf-8 -*-
"""labcycle1_qstion2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mG0L5CkKrqrOE0myqD0XSD2wLr32OChO

2. Develop a program to read the three sides of two triangles and calculate the area of both. Define a function to read the three sides and call it. Also, define a function to calculate the area. Print the total area enclosed by both triangles and each triangle's contribution (%) towards it.
"""

def get_side(): # defining a function to get the to get the sides
  a=int(input("enter side 1"))
  b=int(input("enter side 2"))
  c=int(input("enter side 3"))
  return a,b,c
def area(): # defining a function find the area
  a,b,c=get_side()
  s=(a+b+c)/2
  print(s)
  area=(s*(s-a)*(s-b)*(s-c))**0.5
  print("area is",area)
  return area
def contribution():  # defining a function find the contribution of both triangles
  area1=area()
  area2=area()
  contri1=100*(area1/(area1+area2))

  contri2=100-contri1
  print("contribution of 1st trinagle=",int(contri1),"%\n"+"contribution of 2nt trinagle=",int(contri2),"%",)

contribution()#calling the function