# -*- coding: utf-8 -*-
"""labcycle1_qstion3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SEI_GsEroX8xPaWYZQpaql7L0PXRrJla

3. Develop a program to read the employee's name, code, and basic pay and calculate the gross salary, deduction, and net salary according to the following conditions. Define a function to find each of the components. Finally, generate a payslip.
"""

def empl_det(): #getting employee details
  code=int(input("enter employee code:\t"))
  name=str(input("enter name:\t"))
  sal=int(input("enter employee salary:\t"))
  return code,name,sal
def gross_sal(sal,da,hra,ma):  #function to get gross salary
  gross_sal=sal+sal*(da/100)+sal*(hra/100)+ma
  return gross_sal
def deduction(sal,pt,pf,it):  #fuction to get salary deduction
  deduction=pt+sal*(pf/100)+sal*(it/100)
  return deduction
def net_sal(sal,da,hra,ma,pt,pf,it): #fuction to get net salary
  net_sal=gross_sal(sal,da,hra,ma)-deduction(sal,pt,pf,it)
  print("net salary\t",net_sal)

code,name,sal=empl_det()
if sal<10000:                     # catogorising the persons salary
  net_sal(sal,5,2.5,500,20,8,0)
elif sal<30000:
  net_sal(sal,7.5,5,2500,60,8,0)
elif sal<50000:
  net_sal(sal,11,7.5,5000,60,11,11)
else:
  net_sal(sal,25,11,7000,80,12,20)