# -*- coding: utf-8 -*-
"""3_LabCycle2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRQhxXrRbKgs1bRxQnMcyTdEi3PxpzGT

3. Read the file 'iris.json' as a text file :
 1. Create a list having each line of the file as an element
 2. Convert it into a list of dictionary objects.
 3. Show the details of all flowers whose species is 
"setosa".
 4. Print the minimum petal area and max sepal area in 
each species
 5. Sort the list of dictionaries according to the total area 
are sepal and petal.
"""

import json
f=open("iris.json","r")
fread=f.read().splitlines()
f.close()

#Convert it into a list of dictionary objects.
length=len(fread)
dct= [eval(fread[i].strip(',')) for i in range(1, length - 1)]

for i in dct:
  if i['species']=='setosa':
    print(i)
  i['sepal_area']=i['sepalLength']*i['sepalWidth']
  i['petal_area']=i['petalLength']*i['petalWidth']
  i['total_area']=i['sepal_area']*i['petal_area']

sepal_ar=[]
petal_ar=[]
species_list=[]
for i in dct:
  species_list.append(i['species'])
species_list=list(set(species_list))
for j in range (len(species_list)):
  for k in dct:
    if k['species']==species_list[j]:
      sepal_ar.append(k['sepal_area'])
      petal_ar.append(k['petal_area'])
  print()
  print("The minimum and maximum petal area of ",species_list[j]," is ",round(min(petal_ar),2)," and ",round(max(petal_ar))," respectively.")
  print("The minimum and maximum sepal area of ",species_list[j]," is ",round(min(sepal_ar),2)," and ",round(max(sepal_ar),2)," respectively.")
  sepal_ar=[]
  petal_ar=[]

#sort
sortedList = (sorted(dct, key = lambda i:i['total_area'] ))
for i in sortedList:
  print(i)
